# RAG 시스템 기본 설정 파일

# 기본 경로 설정
paths:
  base_dir: ""  # 자동으로 설정됨
  raw_data_dir: "data/raw"
  processed_data_dir: "data/processed"
  embeddings_dir: "data/embeddings"
  milvus_db_dir: "milvus_db"  # Milvus 관련 임시 데이터 저장 경로

# 임베딩 설정
embedding:
  model: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"  # 기본 다국어 모델 (평가 결과 F1 0.6493 최고 성능)
  korean_models:  # 한국어 특화 모델
    - "FronyAI/frony-embed-small-ko-v1"  # 한국어 전문 임베딩 모델
    - "Legal-LUKE-KO"  # 법률 도메인 특화 모델
    - "BM-K/KoSimCSE-RoBERTa"  # 한국어 SimCSE 모델
    - "klue/roberta-base"  # KLUE RoBERTa 기본 모델
  dimension: 768  # 임베딩 차원 수
  batch_size: 16  # GPU 메모리 한계에 따라 조정 가능
  normalize: true  # 임베딩 정규화 여부

# Milvus 설정
milvus:
  host: "localhost"  # Milvus 서버 호스트
  port: 19530  # Milvus 서버 포트
  user: ""  # 인증 사용자 (빈 문자열은 인증 없음)
  password: ""  # 인증 비밀번호 (빈 문자열은 인증 없음)
  index_type: "HNSW"  # 인덱스 타입 (HNSW, IVF_FLAT, FLAT)
  metric_type: "COSINE"  # 거리 측정 방식 (COSINE, L2, IP)
  auto_id: false  # 자동 ID 생성 여부
  timeout: 30  # 작업 타임아웃 (초)
  index_params:  # HNSW 인덱스 파라미터
    M: 16  # 노드 당 최대 연결 수
    efConstruction: 256  # 인덱스 구축 시 탐색 폭
  search_params:  # 검색 파라미터
    ef: 64  # 검색 시 탐색 폭
  output_fields:  # 검색 결과에서 반환할 필드
    - "id"
    - "text"
    - "doc_id"
    - "source"
    - "page_num"
    - "chunk_id"
    - "parent_chunk_id"
    - "chunk_type"
    - "article_title"
    - "item_marker"
  collection_name: "CI_20060401"  # 기본 콜렉션 이름

# PDF 파싱 설정
pdf_parsing:
  extract_images: true  # 이미지 추출 여부
  image_format: "png"  # 이미지 저장 형식 (png 또는 jpg)
  min_image_size: 100  # 추출할 최소 이미지 크기 (픽셀)
  caption_max_distance: 150  # 이미지와 캡션 사이 최대 거리 (포인트)
  caption_keywords:  # 캡션을 식별하기 위한 키워드 목록
    - "그림"
    - "Figure"
    - "Fig."
    - "표"
    - "Table"
    - "도표"
    - "Chart"
  respect_sections: true  # 섹션 경계를 존중하여 청킹할지 여부

# CSV 파싱 설정
csv_parsing:
  header: true  # 헤더 포함 여부
  encoding: "utf-8"  # 인코딩 방식
  delimiter: ","  # 구분자
  quotechar: "\""  # 인용 문자

# 청킹 설정
chunking:
  # 기본 청킹 설정
  chunk_size: 700  # 청크당 최대 문자 수 (증가)
  chunk_overlap: 150  # 청크 간 겹치는 문자 수 (증가)
  split_by: "sentence"  # 청크 분할 기준 (character, sentence, paragraph)
  sentence_splitter: "kss"  # 한국어 문장 분리 라이브러리 (kss, nltk)
  respect_section_boundaries: true  # 섹션 경계 존중
  
  # Small-to-Big 청킹 설정
  use_small_to_big: true  # Small-to-Big 청킹 전략 사용 여부
  parent_chunk_size: 1400  # 부모 청크 크기
  child_chunk_size: 600  # 자식 청크 크기
  parent_chunk_overlap: 200  # 부모 청크 간 겹치는 문자 수
  child_chunk_overlap: 100  # 자식 청크 간 겹치는 문자 수
  small_chunk_types:  # 작은 청크 타입 목록
    - "item"
    - "item_sub_chunk"
    - "csv_row"
    - "text_block"
  parent_child_linking: true  # 부모-자식 청크 간 연결 설정
  parent_chunk_data_dir: "data/parsed_output"  # 부모 청크 데이터 저장 경로

# 검색 설정
retrieval:
  top_k: 15  # 최적의 검색 결과 수 (증가)
  similarity_threshold: 0.65  # 최소 유사도 임계값 (낮춤)
  similarity_metric: "cosine"  # 유사도 측정 방식 (cosine, dot_product, euclidean)
  hybrid_search: true  # 벡터 검색과 키워드 검색 결합 여부
  hybrid_alpha: 0.7  # 하이브리드 검색에서 벡터 검색 가중치 (0.7 = 70% 벡터, 30% 키워드)
  keyword_boost: 1.5  # 키워드 매치 부스트 값
  reranking: true  # 검색 결과 재순위화 여부
  preserve_original_order: false  # 재순위화 후에도 원래 순서를 일부 보존할지 여부
  reranking_models:  # 재순위화에 사용할 모델
    - "jhgan/ko-sroberta-multitask"  # 한국어 특화 모델 (순위 향상 비율 35.67% 최고 성능)
    - "cross-encoder/ms-marco-MiniLM-L-6-v2"  # 기본 영어 모델 (순위 향상 비율 18.67%)
    - "cross-encoder/mmarco-mMiniLMv2-L12-H384-v1"  # 다국어 모델 (최소 순위 향상 비율 14.67%, 최소 처리시간 0.0544초)
  reranking_batch_size: 32  # 재순위화 배치 크기
  collections: []  # 검색할 컬렉션 목록 (비워두면 기본 컬렉션 사용)
  vector_db_type: "milvus"  # 벡터 데이터베이스 유형 (milvus, pinecone)
  offline_mode: false  # 오프라인 모드 사용 여부 (벡터 DB 연결 없이 더미 결과 반환)
  
  # Small-to-Big 검색 설정
  use_parent_chunks: true  # 부모 청크 사용 여부
  enable_query_optimization: true  # 쿼리 최적화 사용 여부
  optimization_techniques:  # 쿼리 최적화 기법 목록
    - "keyword_extraction"  # 키워드 추출
    - "query_expansion"  # 쿼리 확장
    - "query_reformulation"  # 쿼리 재구성
  
  # Milvus 특화 검색 필터 설정
  filter_expressions:
    default: ""  # 기본 필터 표현식 (비어있으면 필터 없음)
    text_only: "chunk_type in ['text', 'paragraph', 'section', 'title']"  # 텍스트 청크만 검색
    structured_only: "chunk_type in ['table', 'list', 'item']"  # 구조화된 청크만 검색

# 응답 생성 설정
generation:
  model: "grok-3-mini-beta"  # 생성 모델 (Grok API)
  temperature: 0.3  # 낮은 값: 결정적, 높은 값: 다양한 응답
  max_tokens: 1024  # 최대 생성 토큰 수
  response_language: "ko"  # 응답 언어 (ko, en)
  prompt_template: |
    다음 정보를 바탕으로 질문에 답변하세요. 정보에 없는 내용은 '제공된 문서에는 해당 정보가 없습니다.'라고 말하세요.
    
    ### 정보:
    {context}
    
    ### 질문:
    {query}
    
    ### 답변:

# 평가 설정
evaluation:
  metrics:
    - "precision"
    - "recall"
    - "f1_score"
    - "mrr"
    - "ndcg"
  run_settings:
    result_dir: "evaluation_results"
    collection_name: "CI_20060401"
    top_k_values: [5, 10, 15]
    similarity_thresholds: [0.65, 0.7]
    dataset_paths: ["src/evaluation/data/insurance_eval_dataset.json"]
    use_small_to_big_in_eval: true
    enable_query_optimization_in_eval: true
    hybrid_search_in_eval: true
  
  # 임베딩 모델 평가 설정
  embedding_models:
    - name: "sentence-transformers/paraphrase-multilingual-mpnet-base-v2"
      dimension: 768
      normalize: true
    - name: "jhgan/ko-sroberta-multitask"
      dimension: 768
      normalize: true
  
  # 재순위화 모델 평가 설정
  reranker_models:
    - name: "cross-encoder/ms-marco-MiniLM-L-6-v2"
      dimension: 384
    - name: "jhgan/ko-sroberta-multitask"
      dimension: 768
  
  # Milvus 평가 설정
  similarity_metric: "COSINE"
  milvus_index_type: "HNSW"
  milvus_index_params_hnsw:
    M: 16
    efConstruction: 256
  milvus_search_params_hnsw:
    ef: 64
  milvus_output_fields:
    - "id"
    - "text"
    - "doc_id"
    - "source"
    - "page_num"
    - "chunk_id"
    - "parent_chunk_id"
    - "chunk_type"
    - "article_title"
    - "item_marker"

# 일반 설정
general:
  log_level: "INFO"  # 로그 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  language: "ko"  # 기본 언어 (ko, en)
  max_workers: 4  # 병렬 처리 작업자 수
  cache_dir: ".cache"  # 캐시 디렉토리
